### ISSUE TITLE
Issues with Postgres Database

### ISSUE THREAD

**Issue by javedhussain** [timakin/autocompl#1]
I'm using postgres Database. It is not working because in postgres we have ILIKE instead of LIKE of mysql. Please fix it or share the solution if it overridable. 

Thanks

**Comment by timakin** [comment]
Thank you for reporting the critical issue.
Currently I'm trying to fix it.
On `lib/autocompl/repository.rb`, I'll rewrite a where clause with `ILIKE` for a PostgreSQL adapter.
Just a moment, please.

**Comment by timakin** [comment]
@javedhussain 
On v0.2.2, I added `ILIKE` support.
Please try this.

**Comment by javedhussain** [comment]
Thanks for the prompt solution. it is working now.
